"""init

Revision ID: 5d287545fc7b
Revises: 
Create Date: 2026-06-08 11:27:05.664809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d287545fc7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('methode', sa.String(length=20), nullable=True),
    sa.Column('intention', sa.String(length=20), nullable=True),
    sa.Column('heure_reference', sa.Time(), nullable=True),
    sa.Column('mode_decalage', sa.String(length=20), nullable=True),
    sa.Column('seuil_decalage_min', sa.Integer(), nullable=True),
    sa.Column('avertissement_lu', sa.Boolean(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_debut_regles', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycles_user_id'), ['user_id'], unique=False)

    op.create_table('profils_personnels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle_moyen', sa.Float(), nullable=True),
    sa.Column('cycle_min', sa.Integer(), nullable=True),
    sa.Column('cycle_max', sa.Integer(), nullable=True),
    sa.Column('ecart_type_cycle', sa.Float(), nullable=True),
    sa.Column('jour_ovulation_moyen', sa.Float(), nullable=True),
    sa.Column('temp_plateau_bas', sa.Float(), nullable=True),
    sa.Column('temp_plateau_haut', sa.Float(), nullable=True),
    sa.Column('amplitude_saut', sa.Float(), nullable=True),
    sa.Column('heure_prise_habituelle', sa.Time(), nullable=True),
    sa.Column('jour_apparition_glaire_moyen', sa.Float(), nullable=True),
    sa.Column('pct_points_douteux', sa.Float(), nullable=True),
    sa.Column('nb_cycles_enregistres', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_brute', sa.Float(), nullable=True),
    sa.Column('temp_corrigee', sa.Float(), nullable=True),
    sa.Column('heure_prise', sa.Time(), nullable=True),
    sa.Column('douteux', sa.Boolean(), nullable=False),
    sa.Column('motif_doute', sa.String(length=50), nullable=True),
    sa.Column('glaire_sensation', sa.String(length=30), nullable=True),
    sa.Column('glaire_aspect', sa.String(length=30), nullable=True),
    sa.Column('col_hauteur', sa.String(length=20), nullable=True),
    sa.Column('col_ouverture', sa.String(length=20), nullable=True),
    sa.Column('col_consistance', sa.String(length=20), nullable=True),
    sa.Column('saignement', sa.String(length=20), nullable=True),
    sa.Column('union', sa.Boolean(), nullable=False),
    sa.Column('test_lh', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'date', name='uq_observation_cycle_date')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('statuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('feu', sa.String(length=10), nullable=False),
    sa.Column('confiance', sa.String(length=10), nullable=False),
    sa.Column('messages_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statuts')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_cycle_id'))

    op.drop_table('observations')
    op.drop_table('profils_personnels')
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycles_user_id'))

    op.drop_table('cycles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
